# Generated by Django 5.2.14 on 2026-05-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_vocabularycollection_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCollectionWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=255)),
                ('vietnamese_meaning', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.vocabularycollection')),
            ],
            options={
                'db_table': 'vocabulary_collection_words',
            },
        ),
    ]
