# Generated by Django 5.2.14 on 2026-05-16 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_vocabularycollectionword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_study_sessions', to='vocabulary.vocabularycollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vocabulary_study_sessions',
            },
        ),
        migrations.CreateModel(
            name='VocabularyStudyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_study_results', to='vocabulary.vocabularycollectionword')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_study_results', to='vocabulary.vocabularystudysession')),
            ],
            options={
                'db_table': 'vocabulary_study_results',
            },
        ),
    ]
