# Generated by Django 5.2.14 on 2026-05-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_vocabularystudysession_vocabularystudyresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularycollectionword',
            name='word_type',
            field=models.CharField(blank=True, choices=[('noun', 'Danh từ'), ('verb', 'Động từ'), ('adjective', 'Tính từ'), ('adverb', 'Trạng từ'), ('preposition', 'Giới từ'), ('conjunction', 'Liên từ'), ('pronoun', 'Đại từ'), ('interjection', 'Thán từ'), ('other', 'Khác')], max_length=20, null=True),
        ),
    ]
