# Generated by Django 5.2.14 on 2026-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_vocabularycollectionword_word_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularycollectionword',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
