# Generated by Django 5.2.14 on 2026-05-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_vocabularycollectionword_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularycollectionword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vocabulary/words/'),
        ),
    ]
