# Generated by Django 5.2.14 on 2026-05-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_vocabularycollectionword_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularycollectionword',
            name='image',
        ),
    ]
